#!/usr/bin/env node

import nodemailer from 'nodemailer';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import figlet from 'figlet';
import { createInterface } from 'readline';

// ─── Theme ────────────────────────────────────────────────────────────────────
const theme = {
  primary:   chalk.hex('#00D9FF'),
  secondary: chalk.hex('#FF6B35'),
  success:   chalk.hex('#00FF88'),
  error:     chalk.hex('#FF3366'),
  muted:     chalk.hex('#555577'),
  label:     chalk.hex('#AAAACC').bold,
  value:     chalk.hex('#FFFFFF'),
  border:    chalk.hex('#333355'),
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
function banner() {
  console.clear();
  const art = figlet.textSync('SMTP  Tester', { font: 'Slant' });
  console.log(theme.primary(art));
  console.log(theme.muted('  ─────────────────────────────────────────────────────'));
  console.log(theme.muted('  Advanced SMTP diagnostic & test-mail tool · v1.0.0'));
  console.log(theme.muted('  ─────────────────────────────────────────────────────\n'));
}

function sectionHeader(title) {
  console.log('\n' + theme.primary('  ┌─ ') + theme.label(title));
  console.log(theme.primary('  │'));
}

function sectionEnd() {
  console.log(theme.primary('  └────────────────────────────────────\n'));
}

function printSummary(cfg) {
  console.log('\n' + theme.border('  ╔══════════════════════════════════════════╗'));
  console.log(    theme.border('  ║') + theme.primary.bold('       CONNECTION SUMMARY                 ') + theme.border('║'));
  console.log(    theme.border('  ╠══════════════════════════════════════════╣'));

  const row = (k, v) =>
    console.log(theme.border('  ║  ') + theme.label(k.padEnd(14)) + theme.value(String(v).padEnd(28)) + theme.border('║'));

  row('Host',     cfg.host);
  row('Port',     cfg.port);
  row('Security', cfg.security);
  row('User',     cfg.user);
  row('Pass',     '*'.repeat(Math.min(cfg.pass.length, 12)));
  row('From',     cfg.from);
  row('To',       cfg.to);
  row('Subject',  cfg.subject.slice(0, 26) + (cfg.subject.length > 26 ? '…' : ''));

  console.log(theme.border('  ╚══════════════════════════════════════════╝\n'));
}

function buildTransport(cfg) {
  const secure = cfg.security === 'SSL/TLS';
  const starttls = cfg.security === 'STARTTLS';

  return nodemailer.createTransport({
    host: cfg.host,
    port: Number(cfg.port),
    secure,
    auth: { user: cfg.user, pass: cfg.pass },
    tls: {
      rejectUnauthorized: cfg.rejectUnauthorized,
      ...(starttls ? {} : {}),
    },
    requireTLS: starttls,
    connectionTimeout: cfg.timeout * 1000,
    greetingTimeout:   cfg.timeout * 1000,
    socketTimeout:     cfg.timeout * 1000,
  });
}

function buildHtmlBody(cfg) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
<style>
  body { font-family: 'Segoe UI', sans-serif; background:#0a0a1a; color:#e0e0ff; margin:0; padding:0; }
  .wrapper { max-width:600px; margin:40px auto; background:#12122a; border-radius:12px;
             border:1px solid #2a2a5a; overflow:hidden; }
  .header  { background:linear-gradient(135deg,#00D9FF22,#FF6B3522);
             border-bottom:1px solid #2a2a5a; padding:32px; text-align:center; }
  .header h1 { margin:0; font-size:22px; color:#00D9FF; letter-spacing:2px; }
  .body    { padding:32px; }
  .row     { display:flex; justify-content:space-between; border-bottom:1px solid #1e1e3a;
             padding:10px 0; font-size:13px; }
  .key     { color:#8888aa; }
  .val     { color:#ffffff; font-weight:600; }
  .badge   { display:inline-block; background:#00FF8833; color:#00FF88; border:1px solid #00FF88;
             border-radius:20px; padding:4px 16px; font-size:12px; margin-top:24px; }
  .footer  { text-align:center; padding:16px; font-size:11px; color:#44445a; }
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>📡 SMTP TEST SUCCESSFUL</h1>
    <p style="color:#8888aa;margin:8px 0 0">This is an automated diagnostic message</p>
  </div>
  <div class="body">
    <div class="row"><span class="key">From</span><span class="val">${cfg.from}</span></div>
    <div class="row"><span class="key">To</span><span class="val">${cfg.to}</span></div>
    <div class="row"><span class="key">Host</span><span class="val">${cfg.host}:${cfg.port}</span></div>
    <div class="row"><span class="key">Security</span><span class="val">${cfg.security}</span></div>
    <div class="row"><span class="key">Sent at</span><span class="val">${new Date().toISOString()}</span></div>
    <div style="text-align:center"><span class="badge">✓ DELIVERY CONFIRMED</span></div>
  </div>
  <div class="footer">Generated by SMTP Tester CLI · smtp-tester</div>
</div>
</body>
</html>`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  banner();

  // ── SMTP Server ──────────────────────────────────────────────────────────────
  sectionHeader('SMTP SERVER');
  const server = await inquirer.prompt([
    {
      type: 'input',
      name: 'host',
      prefix: theme.primary('  │'),
      message: theme.label('Hostname  '),
      default: 'smtp.gmail.com',
      validate: v => v.trim() ? true : 'Host is required',
    },
    {
      type: 'list',
      name: 'security',
      prefix: theme.primary('  │'),
      message: theme.label('Security  '),
      choices: ['SSL/TLS', 'STARTTLS', 'None'],
      default: 'SSL/TLS',
    },
    {
      type: 'input',
      name: 'port',
      prefix: theme.primary('  │'),
      message: theme.label('Port      '),
      default: ans => ans.security === 'SSL/TLS' ? '465' : ans.security === 'STARTTLS' ? '587' : '25',
      validate: v => /^\d+$/.test(v) && +v > 0 && +v < 65536 ? true : 'Enter a valid port (1–65535)',
    },
    {
      type: 'confirm',
      name: 'rejectUnauthorized',
      prefix: theme.primary('  │'),
      message: theme.label('Verify TLS cert'),
      default: true,
    },
    {
      type: 'number',
      name: 'timeout',
      prefix: theme.primary('  │'),
      message: theme.label('Timeout (s)'),
      default: 15,
      validate: v => v > 0 ? true : 'Must be > 0',
    },
  ]);
  sectionEnd();

  // ── Credentials ──────────────────────────────────────────────────────────────
  sectionHeader('CREDENTIALS');
  const creds = await inquirer.prompt([
    {
      type: 'input',
      name: 'user',
      prefix: theme.primary('  │'),
      message: theme.label('Username  '),
      validate: v => v.trim() ? true : 'Username required',
    },
    {
      type: 'password',
      name: 'pass',
      prefix: theme.primary('  │'),
      message: theme.label('Password  '),
      mask: '●',
      validate: v => v.trim() ? true : 'Password required',
    },
  ]);
  sectionEnd();

  // ── Email ─────────────────────────────────────────────────────────────────────
  sectionHeader('EMAIL');
  const mail = await inquirer.prompt([
    {
      type: 'input',
      name: 'from',
      prefix: theme.primary('  │'),
      message: theme.label('From      '),
      default: creds.user,
      validate: v => /.+@.+\..+/.test(v) ? true : 'Enter a valid email',
    },
    {
      type: 'input',
      name: 'to',
      prefix: theme.primary('  │'),
      message: theme.label('To        '),
      validate: v => /.+@.+\..+/.test(v) ? true : 'Enter a valid email',
    },
    {
      type: 'input',
      name: 'subject',
      prefix: theme.primary('  │'),
      message: theme.label('Subject   '),
      default: `SMTP Test · ${new Date().toLocaleString()}`,
    },
    {
      type: 'list',
      name: 'bodyType',
      prefix: theme.primary('  │'),
      message: theme.label('Body type '),
      choices: ['HTML (styled)', 'Plain text'],
      default: 'HTML (styled)',
    },
    {
      type: 'input',
      name: 'customText',
      prefix: theme.primary('  │'),
      message: theme.label('Custom msg'),
      default: '',
      when: ans => ans.bodyType === 'Plain text',
    },
  ]);
  sectionEnd();

  // ── Summary & Confirm ─────────────────────────────────────────────────────────
  const cfg = { ...server, ...creds, ...mail };
  printSummary(cfg);

  const { confirmed } = await inquirer.prompt([{
    type: 'confirm',
    name: 'confirmed',
    prefix: theme.secondary('  ►'),
    message: theme.secondary.bold('Send test email now?'),
    default: true,
  }]);

  if (!confirmed) {
    console.log('\n' + theme.muted('  Aborted. No email sent.\n'));
    process.exit(0);
  }

  // ── Send ──────────────────────────────────────────────────────────────────────
  console.log();
  const transport = buildTransport(cfg);

  // Step 1: verify connection
  const spinVerify = ora({
    text: theme.primary('Connecting to SMTP server…'),
    spinner: 'dots12',
    color: 'cyan',
    prefixText: '  ',
  }).start();

  try {
    await transport.verify();
    spinVerify.succeed(theme.success('Connection verified ✓'));
  } catch (err) {
    spinVerify.fail(theme.error('Connection failed ✗'));
    console.log('\n' + theme.error('  Error: ') + theme.value(err.message));
    if (err.code) console.log(theme.muted('  Code:  ') + err.code);
    if (err.response) console.log(theme.muted('  SMTP:  ') + err.response);
    console.log();
    process.exit(1);
  }

  // Step 2: send
  const spinSend = ora({
    text: theme.primary('Sending email…'),
    spinner: 'dots12',
    color: 'cyan',
    prefixText: '  ',
  }).start();

  try {
    const isHtml = cfg.bodyType === 'HTML (styled)';
    const info = await transport.sendMail({
      from: cfg.from,
      to: cfg.to,
      subject: cfg.subject,
      ...(isHtml
        ? { html: buildHtmlBody(cfg), text: 'SMTP test successful.' }
        : { text: cfg.customText || 'SMTP test successful.' }),
    });

    spinSend.succeed(theme.success('Email sent successfully ✓'));

    console.log('\n' + theme.border('  ┌──────────────────────────────────────────┐'));
    console.log(    theme.border('  │') + theme.success.bold('  ✓ DELIVERY REPORT                        ') + theme.border('│'));
    console.log(    theme.border('  ├──────────────────────────────────────────┤'));

    const dRow = (k, v) =>
      console.log(theme.border('  │  ') + theme.label(k.padEnd(14)) + theme.value(String(v || '—').slice(0, 28).padEnd(28)) + theme.border('│'));

    dRow('Message ID', info.messageId);
    dRow('Response',   info.response);
    dRow('Accepted',   info.accepted?.join(', '));
    if (info.rejected?.length) dRow('Rejected', info.rejected.join(', '));

    console.log(theme.border('  └──────────────────────────────────────────┘\n'));

  } catch (err) {
    spinSend.fail(theme.error('Send failed ✗'));
    console.log('\n' + theme.error('  Error: ') + theme.value(err.message));
    if (err.responseCode) console.log(theme.muted('  Code:  ') + err.responseCode);
    if (err.response)     console.log(theme.muted('  SMTP:  ') + err.response);
    console.log();
    process.exit(1);
  }

  // ── Run again? ────────────────────────────────────────────────────────────────
  const { again } = await inquirer.prompt([{
    type: 'confirm',
    name: 'again',
    prefix: theme.muted('  ►'),
    message: theme.muted('Run another test?'),
    default: false,
  }]);

  if (again) {
    await main();
  } else {
    console.log(theme.muted('\n  Bye! 👋\n'));
  }
}

main().catch(err => {
  console.error(theme.error('\n  Fatal: ') + err.message);
  process.exit(1);
});